#!/usr/bin/env python3
"""Render one project's prompt tickets into its own TODO.md, and detect drift.

WHY A GENERATED BLOCK AND NOT A GENERATED FILE. `TODO.md` here is 691 lines whose
hand-written bodies carry reasoning that exists nowhere else. Regenerating it would
destroy that, which is the excavation failure the lifecycle spec was written to avoid.
So this writes between two markers and never touches a byte outside them, and a repo
with no markers gets them appended once.

WHY PER PROJECT. The store is estate-wide: 1,127 tickets across 191 sessions and a
dozen repositories. A single list of all of them is not a todolist for anybody. The
docs control plane says one TODO per repo, so the slice is by `events.repo_path` and
the output goes to that repo's own file. That is also what makes this usable from
outside this repository: point `--project` at another checkout and it renders that
checkout's prompts into that checkout's TODO.

WHAT IT WILL NOT DO. It does not promote anything. A `CAPTURED` ticket is rendered as
awaiting triage, in the operator's own words, and nothing here writes a transition. The
counts are the honest surface: a backlog you can see is a backlog, and one you cannot is
a loss.

THE PATH PROBLEM. The same repository appears in the store as
`C:\\Users\\shova\\Downloads\\new-recruit` and `/home/shov/work/repos/new-recruit`,
because the estate moved from Windows to WSL mid-history. Matching on the full path
would split one project's history in two and under-report every count. `project_key`
compares trailing path segments instead, which is lossy in the other direction and is
the direction that shows the operator more of their own work rather than less.
"""
from __future__ import annotations

import argparse
import json
import re
import sqlite3
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT / "tools" / "intent") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "tools" / "intent"))

import tickets  # noqa: E402

BEGIN = "<!-- prompt-tickets:begin generated by tools/intent/render_todo.py, do not hand-edit -->"
END = "<!-- prompt-tickets:end -->"

# States a human can act on today. Everything else is either noise the classifier named
# or a prompt nobody has read yet, and both are reported as counts rather than as rows.
WORKABLE = ("OPEN", "IN_PROGRESS", "BLOCKED_OPERATOR")

# How many untriaged prompts the block lists. A cap is necessary (a project with 500
# untriaged prompts would bury the hand-written TODO under its own inbox) and a silent
# one is a lie, so the rendered text always states the total next to the cap.
TRIAGE_WINDOW = 12


def project_key(path: str) -> str:
    """The comparable name of a repository, from a path in either OS's spelling.

    Trailing segment, with a parent prefix kept when the leaf is a generic word. Without
    that, `daily-deep-learning/daemon` and any other `daemon` collapse together, and a
    subproject's prompts would be filed under whichever repo asked first.
    """
    parts = [p for p in str(path).replace("\\", "/").split("/") if p and p != "."]
    if not parts:
        return ""
    leaf = parts[-1]
    generic = {"daemon", "src", "app", "server", "api", "web", "backend", "frontend",
               "docs", "tools", "scripts"}
    if leaf.lower() in generic and len(parts) >= 2:
        return f"{parts[-2]}/{leaf}".lower()
    return leaf.lower()


def resolve_project(path: Path) -> Path:
    """The repository a checkout belongs to, following a worktree back to its parent.

    Found the hard way on this tool's own first run: inside
    `.claude/worktrees/lane-a+session-prompt-db-and-per-project-todo` the key became the
    worktree's name, matched no `repo_path` in the store, and the block rendered "no
    prompt tickets recorded" for a repository holding 310 of them. An empty result that
    looks like an answer is the failure mode worth spending a subprocess on.

    `--git-common-dir` is the ordinary worktree's pointer home; in a primary checkout it
    resolves to that checkout's own `.git`, so one call covers both cases.
    """
    import subprocess

    try:
        out = subprocess.run(
            ["git", "-C", str(path), "rev-parse", "--path-format=absolute",
             "--git-common-dir"],
            capture_output=True, text=True, timeout=5, check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return path
    common = out.stdout.strip()
    if out.returncode != 0 or not common:
        return path
    root = Path(common).parent
    return root if root.exists() else path


def load(base_dir: Path | None = None) -> list[dict[str, Any]]:
    """Every ticket in the store, with its newest state and its prompt text.

    Read through plain sqlite rather than the package, so this runs from any repository
    under the system interpreter with nothing installed. That is the whole point of the
    tool being usable outside this one.
    """
    base = base_dir or (Path.home() / ".intent")
    db = base / "intent.db"
    if not db.exists():
        return []
    conn = sqlite3.connect(f"file:{db}?mode=ro", uri=True)
    conn.row_factory = sqlite3.Row
    try:
        rows = conn.execute(
            """
            select e.bead_id      as ticket,
                   e.session_id   as session,
                   e.repo_path    as repo,
                   e.timestamp_utc as ts,
                   e.model_text   as text,
                   (select c.goal from intent_cards c where c.event_id = e.event_id
                     limit 1) as goal,
                   (select t.to_state from state_transitions t
                     where t.subject_id = e.bead_id
                     order by t.created_at_utc desc, t.rowid desc limit 1) as state,
                   (select t.reason from state_transitions t
                     where t.subject_id = e.bead_id
                     order by t.created_at_utc desc, t.rowid desc limit 1) as reason
              from events e
             where e.bead_id like 'PT-%'
             order by e.timestamp_utc
            """
        ).fetchall()
    except sqlite3.Error:
        return []
    finally:
        conn.close()
    return [dict(r) for r in rows]


def for_project(rows: list[dict[str, Any]], project: str) -> list[dict[str, Any]]:
    """The subset belonging to one project, by the lossy key above."""
    key = project_key(project)
    return [r for r in rows if project_key(r.get("repo") or "") == key]


def summarize(rows: list[dict[str, Any]]) -> dict[str, Any]:
    """Split a project's tickets into workable, noise, and awaiting triage."""
    workable, noise, untriaged = [], [], []
    triaged: dict[str, int] = {}
    not_work = 0
    for row in rows:
        state = row.get("state") or tickets.GENESIS
        if state in WORKABLE:
            workable.append(row)
        elif state == tickets.GENESIS:
            klass, _ = tickets.classify(row.get("text") or "")
            (noise if klass else untriaged).append(row)
        elif state == "TRIAGED":
            # The transition reason names where the ticket went ("issue #91"). Grouping
            # by that keeps the inbox pointing at the checklist instead of going blank
            # the moment everything is triaged, which is what happened on 2026-08-23.
            m = re.search(r"issue #(\d+)", row.get("reason") or "")
            key = f"#{m.group(1)}" if m else "(no issue named)"
            triaged[key] = triaged.get(key, 0) + 1
        elif state == "NOT_WORK":
            not_work += 1
    untriaged.sort(key=lambda r: r.get("ts") or "", reverse=True)
    return {
        "total": len(rows),
        "workable": workable,
        "noise": len(noise),
        "untriaged": untriaged,
        "triaged": triaged,
        "not_work": not_work,
        "sessions": len({r.get("session") for r in rows}),
    }


def _one_line(row: dict[str, Any], width: int = 96) -> str:
    """The prompt on one line. The operator's words, never a paraphrase."""
    text = " ".join((row.get("text") or row.get("goal") or "").split())
    if len(text) > width:
        text = text[: width - 1].rstrip() + "\u2026"
    return text or "(no text recorded)"


def render(project: str, rows: list[dict[str, Any]]) -> str:
    """The generated block, marker to marker."""
    s = summarize(rows)
    name = project_key(project) or project
    out = [BEGIN, "", f"## Prompt inbox: {name}", ""]
    if not rows:
        out += [f"No prompt tickets recorded for `{name}`. Either nothing was typed "
                "against this checkout, or capture is not running here.", "", END]
        return "\n".join(out)

    date = (s["untriaged"][0].get("ts") or "")[:10] if s["untriaged"] else "n/a"
    out.append(
        f"{s['total']} prompts across {s['sessions']} sessions. "
        f"{len(s['workable'])} workable, {len(s['untriaged'])} awaiting triage "
        f"(newest {date}), {s['noise']} classified as slash commands or acks by rule."
    )
    out.append("")

    if s["triaged"]:
        total_triaged = sum(s["triaged"].values())
        out.append(f"### Triaged into checklist issues, {total_triaged} prompts")
        out.append("")
        out.append("One box per prompt lives on the issue; the ticket's state moves when the box does. "
                   f"{s['not_work']} prompts were marked not work (acks, status checks, notifications).")
        out.append("")
        for key, n in sorted(s["triaged"].items(), key=lambda kv: (-kv[1], kv[0])):
            out.append(f"- {key}: {n} prompts")
        out.append("")

    if s["workable"]:
        out.append("### Workable")
        for row in s["workable"]:
            out.append(f"- [ ] `{row['ticket']}` `{row.get('state')}` "
                       f"{(row.get('ts') or '')[:10]} {_one_line(row)}")
        out.append("")

    if s["untriaged"]:
        shown = s["untriaged"][:TRIAGE_WINDOW]
        out.append(f"### Awaiting triage, newest {len(shown)} of {len(s['untriaged'])}")
        out.append("")
        out.append("Verbatim prompts, not yet promoted to work. Nothing here has been "
                   "read by the machine that wrote it.")
        out.append("")
        for row in shown:
            out.append(f"- [ ] `{row['ticket']}` {(row.get('ts') or '')[:10]} "
                       f"{_one_line(row)}")
        if len(s["untriaged"]) > len(shown):
            out.append("")
            out.append(f"{len(s['untriaged']) - len(shown)} older untriaged prompts are "
                       "not listed here. Read them with "
                       "`python tools/intent/render_todo.py list --project .`.")
        out.append("")
    out.append(END)
    return "\n".join(out)


def splice(existing: str, block: str) -> str:
    """Put the block between the markers, appending them once if they are absent."""
    if BEGIN in existing and END in existing:
        head = existing.split(BEGIN)[0]
        tail = existing.split(END, 1)[1]
        return head + block + tail
    sep = "" if existing.endswith("\n\n") or not existing else (
        "\n" if existing.endswith("\n") else "\n\n")
    return existing + sep + "\n" + block + "\n"


def todo_path(project: Path) -> Path:
    return project / "TODO.md"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("command", choices=("write", "check", "list", "selftest"),
                        nargs="?", default="write")
    parser.add_argument("--project", type=Path, default=Path.cwd(),
                        help="repository to render for; defaults to the current directory")
    parser.add_argument("--todo", type=Path, help="override the TODO.md path")
    parser.add_argument("--base-dir", type=Path, help="intent store to read")
    parser.add_argument("--limit", type=int, default=40, help="rows for `list`")
    args = parser.parse_args(argv)

    if args.command == "selftest":
        return selftest()

    # Two different questions, and conflating them wrote this repository's block into the
    # shared checkout while running inside a worktree. WHICH PROMPTS is asked of the
    # parent repository, because a worktree's prompts are the repo's prompts. WHICH FILE
    # is asked of the directory the caller named, because writing outside the checkout
    # you were pointed at defeats the isolation a worktree exists to provide.
    checkout = args.project.resolve()
    project = resolve_project(checkout)

    base = args.base_dir or (Path.home() / ".intent")
    store_db = base / "intent.db"
    if args.command == "check" and not store_db.exists():
        print(f"CANNOT MEASURE: intent store not found at {store_db}")
        return 2

    rows = for_project(load(args.base_dir), str(project))

    if args.command == "list":
        s = summarize(rows)
        for row in s["untriaged"][: args.limit]:
            print(f"{row['ticket']}  {(row.get('ts') or '')[:16]}  {_one_line(row, 140)}")
        print(f"\n{len(s['untriaged'])} awaiting triage, {len(s['workable'])} workable, "
              f"{s['noise']} rule-classified, {s['total']} total")
        return 0

    block = render(str(project), rows)
    target = args.todo or todo_path(checkout)
    existing = target.read_text(encoding="utf-8") if target.exists() else ""
    updated = splice(existing, block)

    if args.command == "check":
        if existing == updated:
            print(f"TODO block current for {project_key(str(project))}")
            return 0
        if BEGIN not in existing:
            print(f"DRIFT {target}: no generated block. Run `render_todo.py write`.")
        else:
            print(f"DRIFT {target}: the generated block does not match the store. "
                  "Run `render_todo.py write`.")
        return 1

    target.write_text(updated, encoding="utf-8")
    s = summarize(rows)
    print(f"wrote {target}: {s['total']} tickets, {len(s['workable'])} workable, "
          f"{len(s['untriaged'])} awaiting triage, {s['noise']} rule-classified")
    return 0


def selftest() -> int:
    """Prove the splice preserves hand-written text and that check catches drift."""
    import tempfile

    failures: list[str] = []

    if project_key("C:\\Users\\shova\\Downloads\\new-recruit") != "new-recruit":
        failures.append("a Windows path did not reduce to its project name")
    if project_key("/home/shov/work/repos/new-recruit") != "new-recruit":
        failures.append("a POSIX path did not reduce to its project name")
    if project_key("/a/daily-deep-learning/daemon") == project_key("/b/other/daemon"):
        failures.append("two different `daemon` subprojects collapsed to one key")
    here = Path(__file__).resolve().parent
    if project_key(str(resolve_project(here))) != "claude-setup":
        failures.append(
            f"a worktree did not resolve to its parent repository: "
            f"{project_key(str(resolve_project(here)))}")

    rows = [
        {"ticket": "PT-a", "session": "s1", "repo": "/x/demo", "ts": "2026-08-01T00:00:00Z",
         "text": "rewrite the parser", "goal": "rewrite the parser", "state": "CAPTURED"},
        {"ticket": "PT-b", "session": "s1", "repo": "/x/demo", "ts": "2026-08-02T00:00:00Z",
         "text": "/compact", "goal": "", "state": "CAPTURED"},
        {"ticket": "PT-c", "session": "s2", "repo": "/other/thing", "ts": "2026-08-03T00:00:00Z",
         "text": "not this project", "goal": "", "state": "CAPTURED"},
    ]
    mine = for_project(rows, "/somewhere/else/demo")
    if len(mine) != 2:
        failures.append(f"project slice kept {len(mine)} rows, expected 2")
    s = summarize(mine)
    if s["noise"] != 1 or len(s["untriaged"]) != 1:
        failures.append(f"summary split wrong: {s['noise']} noise, "
                        f"{len(s['untriaged'])} untriaged, expected 1 and 1")

    with tempfile.TemporaryDirectory() as tmp:
        todo = Path(tmp) / "TODO.md"
        handwritten = "# TODO\n\n- [ ] a hand-written item nothing may destroy\n"
        todo.write_text(handwritten, encoding="utf-8")
        block = render("/x/demo", mine)

        once = splice(todo.read_text(), block)
        todo.write_text(once, encoding="utf-8")
        if handwritten not in todo.read_text():
            failures.append("the first splice destroyed hand-written text")
        if "rewrite the parser" not in todo.read_text():
            failures.append("the block did not carry the prompt into the file")
        if "/compact" in todo.read_text():
            failures.append("a rule-classified prompt was rendered as a work item")

        twice = splice(todo.read_text(), block)
        if twice != once:
            failures.append("re-splicing is not idempotent")
        if twice.count(BEGIN) != 1:
            failures.append(f"{twice.count(BEGIN)} begin markers after two splices")

        absent_store = main(["check", "--project", tmp, "--todo", str(todo),
                             "--base-dir", str(Path(tmp) / "no-store")])
        if absent_store != 2:
            failures.append(f"check against absent store returned {absent_store}, expected 2")

        if todo_path(Path(tmp)) != Path(tmp) / "TODO.md":
            failures.append("the write target is not the checkout that was named")

        todo.write_text(once.replace("rewrite the parser", "something else"),
                        encoding="utf-8")
        if splice(todo.read_text(), block) == todo.read_text():
            failures.append("check would not notice an edited generated block")

    for line in failures:
        print(f"FAIL {line}")
    if not failures:
        print("PASS render_todo selftest (10 checks)")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
